version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3093:80"
    depends_on:
      - backend
    networks:
      - coc01_network

  backend:
    image: fastapi_01:latest
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8093:8000"
    environment:
      - MONGODB_SYSTEM_URL=mongodb://mongodb:27017/call_of_cthulhu_system
      - MONGODB_URL=mongodb://mongodb:27017/call_of_cthulhu_gamerecords
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://host.docker.internal:11434
    depends_on:
      - mongodb
      - qdrant
    networks:
      - coc01_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5693:5678"
    environment:
      - DB_TYPE=sqlite
      - DB_SQLITE_POOL_SIZE=3
      - N8N_HOST=0.0.0.0
      - WEBHOOK_URL=http://localhost:5678/
      - OLLAMA_HOST=http://host.docker.internal:11434
    volumes:
      - ./n8n:/home/node/.n8n
    networks:
      - coc01_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongodb:
    image: mongo:latest
    command: mongod --noauth
    volumes:
      - ./database/mongodb:/data/db
    ports:
      - "27093:27017"
    networks:
      - coc01_network

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - ./database/qdrant:/qdrant/storage
    ports:
      - "6393:6333"
    networks:
      - coc01_network

networks:
  coc01_network:
    driver: bridge
